version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        volumes:
            - /storage/app-data/couchpotato:/config
            - /storage/.downloads/complete:/storage/.downloads/complete
            - /storage/movies:/storage/movies
        ports:
            - 5050:5050
        environment:
            - VIRTUAL_HOST=couchpotato.vitalogy.duckdns.org
            - VIRTUAL_PORT=5050
            - PUID=1000
            - PGID=1000
        restart: always

    plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: host
        volumes:
            - /storage/app-data/plex:/config
            - /storage/tv:/storage/tv
            - /storage/movies:/storage/movies
            - /storage:/storage
            - /storage/tmp:/tmp
        environment:
            - VIRTUAL_HOST=plex.vitalogy.duckdns.org
            - VIRTUAL_PORT=32400
            - PUID=1000
            - PGID=1000
            - version=docker
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /storage/app-data/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /storage/tv:/storage/tv
            - /storage/.downloads/complete:/storage/.downloads/complete
        ports:
            - 8989:8989
        environment:
            - VIRTUAL_HOST=sonarr.vitalogy.duckdns.org
            - VIRTUAL_PORT=8989
            - PUID=1000
            - PGID=1000
        restart: unless-stopped

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /storage/app-data/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - /storage/app-data/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        environment:
            - VIRTUAL_HOST=plexpy.vitalogy.duckdns.org
            - VIRTUAL_PORT=8181
            - PUID=1000
            - PGID=1000
        restart: unless-stopped

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /storage/app-data/nzbhydra:/config
            - /storage/.downloads/complete:/storage/.downloads/complete
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        environment:
            - VIRTUAL_HOST=nzbhydra.vitalogy.duckdns.org
            - VIRTUAL_PORT=5075
            - PUID=1000
            - PGID=1000
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /storage/app-data/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - VIRTUAL_HOST=muximux.vitalogy.duckdns.org
            - PUID=1000
            - PGID=1000
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /storage/app-data/radarr:/config
            - /storage/movies:/storage/movies
            - /storage/.downloads:/storage/.downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        environment:
            - VIRTUAL_HOST=radarr.vitalogy.duckdns.org
            - VIRTUAL_PORT=7878
            - PUID=1000
            - PGID=1000
        restart: always

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /storage/app-data/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        environment:
            - VIRTUAL_HOST=ombi.vitalogy.duckdns.org
            - VIRTUAL_PORT=3579
            - PUID=1000
            - PGID=1000
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /storage/app-data/nzbget:/config
            - /storage/.downloads/complete:/storage/.downloads/complete
            - /storage/.downloads:/storage/.downloads
            - /storage:/storage
        ports:
            - 6789:6789
        environment:
            - VIRTUAL_HOST=nzbget.vitalogy.duckdns.org
            - VIRTUAL_PORT=6789
            - PUID=1000
            - PGID=1000
        restart: always

    duckdns:
      image: linuxserver/duckdns
      container_name: duckdns
      restart: always
      environment:
        - TZ=America/Toronto
        - PUID=1000
        - PGID=1000
        - TOKEN=5beb6ead-c7cf-4974-960e-7644e5ea1088
        - SUBDOMAINS=vitalogy
        - LOG_FILE=true
      volumes:
        - /storage/app-data/duckdns:/config
    
    telly:
      image: tellytv/telly
      ports:
        - "6077:6077"
      environment:
        - TZ=America/Toronto
        - TELLY_IPTV_PLAYLIST=http://aaaa.agency:83/get.php?username=7040440332&password=yE0d72gaU5&output=ts&type=m3u_plus
        - TELLY_FILTER_REGEX=''
        - TELLY_WEB_LISTEN_ADDRESS=telly:6077
        - TELLY_IPTV_STREAMS=1
        - TELLY_DISCOVERY_FRIENDLYNAME=Tuner1
        - TELLY_DISCOVERY_DEVICEID=12345678
      command: -web.base=telly:6077
      restart: unless-stopped
